{% set python_min = "3.10" %}
{% set name = "hklpy2" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/hklpy2-{{ version }}.tar.gz
  sha256: 63875a55decf5d808daa5549bf627bfe5b51894166f6154b00bedda15fa61f41

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  entry_points:
    - no_op = hklpy2.backends.no_op:NoOpSolver
    - hkl_soleil = hklpy2.backends.hkl_soleil:HklSolver
    - th_tth = hklpy2.backends.th_tth_q:ThTthSolver
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - conda-verify
    - setuptools-scm >=8
    - setuptools >=77.1
    - pip
  run:
    - python >={{ python_min }}
    - bluesky
    - bluesky-tiled-plugins
    - databroker <1.999
    - hkl
    - numpy
    - ophyd
    - packaging
    - pandas
    - pint
    - pyRestTable
    - ruamel.yaml
    - tiled
    - tqdm
    - typeguard

test:
  imports:
    - hklpy2
    - ruamel.yaml
  commands:
    - pip  check
    - python -c "import hklpy2; assert len(hklpy2.solvers())==3; print(hklpy2.solvers())"
  requires:
    - bluesky-tiled-plugins
    - conda-verify
    - pip
    - python {{ python_min }}
    - tiled

about:
  home: https://blueskyproject.io/hklpy2/
  summary: 2nd generation controls for diffractometers as PseudoPositioners in the Bluesky Framework.
  license: BSD-4-Clause
  license_file: LICENSE
  doc_url: https://blueskyproject.io/hklpy2/
  dev_url: https://github.com/bluesky/hklpy2

extra:
  recipe-maintainers:
    - prjemian
